### ISSUE TITLE
[minor] Thread documentation incorrect

### ISSUE THREAD

**Issue by pR0Ps** [RecursiveForest/whatmp3#14]
Currently the README and help text say the default number of cores is 1 while the program actually [defaults to the number of CPU cores your machine has available.](https://github.com/RecursiveForest/whatmp3/blob/5dbfe58d3ea3ef535f1ad31ce09bd5e1a3386988/whatmp3#L43)

**Comment by RecursiveForest** [comment]
Fixed, thanks. :)
