### ISSUE TITLE
Parameter Expansion Bug

### ISSUE THREAD

**Issue by collinjsimpson** [RecursiveForest/whatmp3#16]
Input is improperly escaped before being inserted into `os.system` calls. In particular, whatmp3 chokes on filenames containing the `$` symbol, as the shell interprets the dollar sign as the beginning of a shell parameter.

A fix may involve using *single* quotes to surround parameters (shell expansion doesn't occur within single quotes), or possibly by using `subprocess.Popen` in place of `os.system`, subprocess being safer and more reliable. Parameters need not be escaped when using `subprocess.Popen`, if that is of interest.

A similar change was made in a fork of this project (64bbec779a59a2fac1951f3a3238c618cac14da9). Thanks!

**Comment by RecursiveForest** [comment]
Thanks for the report, still got some inappropriate intuitions from Perl. I believe I've fixed this in https://github.com/RecursiveForest/whatmp3/commit/ec5cc081cba7c4b929c97c4045d5e7b6bccb3ccc .

As I have mentioned elsewhere, subprocess and pipes lead to some disappointing performance, so I won't be trying that merge again. See https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/ .
