### ISSUE TITLE
make a note about requirements of python3 and gmake

### ISSUE THREAD

**Issue by aeuae** [RecursiveForest/whatmp3#17]
Hi, thank you very much for this script, and improving it again!
I just figured out that on my freebsd box, which has bsdmake installed, the line "make install clean" doesn't work.

Using 'gmake clean install' worked just fine.

Maybe you could add a sentence in the readme to give others a heads-up when they are running into the same situation as me that gmake is required (at least that's my assumption).

And, 2 minutes after first posting this issue, I noticed that the standard python on freebsd 10 (which is still python2) would throw this error:
```python
  File "/usr/local/bin/whatmp3", line 157
    print("ERROR: %s: %s" % (r, msg), file=sys.stderr)
                                          ^
SyntaxError: invalid syntax
```
so I did went and installed python3 (v3.4 in my case) and tada: i'm now in transcoding heaven!

is python3 actually required? if yes it would probably a good idea to explain it along with the other requirements.

**Comment by RecursiveForest** [comment]
Thanks for bringing this to my attention; in https://github.com/RecursiveForest/whatmp3/commit/a8f8c509ea3570a5e86628b111d1cace96f7c8c7 I updated the shebang to require python3, and added a note in the README about requiring gmake.
