### ISSUE TITLE
.DS_Store files could be automatically omitted from torrents

### ISSUE THREAD

**Issue by jvacek** [RecursiveForest/whatmp3#23]
Often enough rars contain hidden .DS_Store files which causes torrents not to be accepted by the tracker. Would be nice if the script could automatically discard them from the torrents.

**Comment by RecursiveForest** [comment]
Added the option to ignore dotfiles with -H / --nodots in https://github.com/RecursiveForest/whatmp3/commit/89c2d79d57436af3248aa3c3e93b81ebb1a945d3
