### ISSUE TITLE
SyntaxError: Invalid Syntax with any command

### ISSUE THREAD

**Issue by Qwerty-Space** [RecursiveForest/whatmp3#24]
This is the error:

```
  File "/usr/local/bin/whatmp3", line 157
    print("ERROR: %s: %s" % (r, msg), file=sys.stderr)
```

Thank you!

**Comment by pkovac** [comment]
At a guess, looks like you're trying to run it with python 2.x. Does it work with python 3?

**Comment by Qwerty-Space** [comment]
@pkovac I was in fact on python 2, I just updated to python 3, and:

![image](https://cloud.githubusercontent.com/assets/6967592/17786212/b9312414-657b-11e6-9eb5-6ffc8ce4ce5c.png)

**Comment by RecursiveForest** [comment]
Are you sure you're invoking it with python3?

**Comment by RecursiveForest** [comment]
Additionally, what version are you using? It doesn't look like you're using git head.

**Comment by Qwerty-Space** [comment]
I'm using WhatMP3 version 3.7.
And how would I invoke it with python 3?

**Comment by RecursiveForest** [comment]
Type `python3 /usr/local/bin/whatmp3'; and unfortunately most versions are labeled 3.7 right now. Consider getting a version directly from git.

**Comment by Qwerty-Space** [comment]
So, how would I upgrade, and make it work by just typing ```whatmp3 [command]```?

**Comment by Qwerty-Space** [comment]
Typing ```python3 /usr/local/bin/whatmp3 [command]``` works by the way

**Comment by RecursiveForest** [comment]
Regarding upgrading is a matter of using your package manager. Check out your distro's documentation. Alternative you can `git clone http://github.com/RecursiveForest/whatmp3` and then run `sudo make install`.

If you still have trouble running the script, edit the first line of the script to read `#!/usr/bin/python3`.

**Comment by Qwerty-Space** [comment]
I've already downloaded whatmp3 tar.gz file and run ```sudo make install``` I followed the instructions in the readme

**Comment by Qwerty-Space** [comment]
Which file do I need to edit?

**Comment by RecursiveForest** [comment]
whatmp3.py

**Comment by Qwerty-Space** [comment]
I ran ```sudo nano /usr/local/bin/whatmp3``` and changed the first line to read ```#!/usr/bin/python3``` and made a backup of the old one.
