### ISSUE TITLE
FLAC Japanese kanji tags get mangled in resulting mp3s

### ISSUE THREAD

**Issue by rpgdev** [RecursiveForest/whatmp3#31]
On debian 8 linux the kanji tags of a flac get mangled even after I updated the script to use metaflac with the --no-utf8-convert option. Can you fix this?

**Comment by RecursiveForest** [comment]
Can you show me the tags? Can you show me the output of `locale`?

**Comment by rpgdev** [comment]
This is the output of locale:
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8

How do you want me to show you the tags? Is there a cli tool that I could use to extract them? I don't have the files on my pc now but the tags look like gibberish mostly. When I run the script on my pc the problem doesn't happen though. Locale on PC (ubuntu 14.04):
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=

**Comment by RecursiveForest** [comment]
Yeah, having the tags would be great.

**Comment by rpgdev** [comment]
I don't even have the files now. Try any mp3 files from japanese artists I guess.

**Comment by RecursiveForest** [comment]
I've tested this locally with a few files containing both kanji and katakana and seem to think this is an issue with the existing tags / encoding / locale on rpgdev's machine and am going to close this. If anyone can find a reproducible case of encoding issues with CJK or any other character set I'll do my best to fix it.
