### ISSUE TITLE
Flip --copyother, or add inverse

### ISSUE THREAD

**Issue by Ghosthree3** [RecursiveForest/whatmp3#32]
Given that the default value for copyother in whatmp3.py is in fact 1 these flags are useless by default. Could you either change the flag to be --nocopyother, add an extra flag to do so on top of the existing one, or change the default value to 0.

As it is the script is entirely usable without editing the file in any way except for this, so if you pull the file (like to update) you can immediately use an alias or script with the correct override flags to make everything work. But if you want copyother to be off you HAVE to edit the script and change it to 0. Ideally I'd just like to be able to add a flag to my script to do so.

**Comment by RecursiveForest** [comment]
Thanks for the issue report. I've pushed a fix here: https://github.com/RecursiveForest/whatmp3/commit/5bd150bcf52db777efba1beb00669521753922f7
