### ISSUE TITLE
Pad track numbers to always have two digits

### ISSUE THREAD

**Issue by skorasaurus** [RecursiveForest/whatmp3#34]
Hi, 

This is sort of a lazy feature request, but it'd be rad for the transcoded files to have padded track numbers. 
What this means is that if the original FLAC file's vorbis tag has "1" for the track number field and a file name of "1 - trackttile.flac"; the resultant transcoded files would have 01 in the tag and have the file name of "01 - tracktitle.mp3" 

This is a best practice, so when you're sorting files, double digit track numbers (11, 10) aren't listed before 1.

**Comment by murlakatamenka** [comment]
Padding is available as of the moment of writing:

https://github.com/RecursiveForest/whatmp3/blob/6b0fe1ec60881a48c0a3b18eb57fd8a388c60a43/whatmp3.py#L26-L27
https://github.com/RecursiveForest/whatmp3/blob/6b0fe1ec60881a48c0a3b18eb57fd8a388c60a43/whatmp3.py#L243-L245

I would disagree that padding a `tracknumber` tag is the best practice though. In any sane language if we compare `'1'` and `'10'` string literals this will be true: `'1' < '10'`. So virtually any software asked to sort tracks by its `tracknumber` tag will do such job as you expect it to. Hence padding `traknumber` tag is redundant.

Padding track numbers in file names is undoubtedly useful and can be recommended to one and every.

Anyway, this issue can be closed @RecursiveForest

**Comment by murlakatamenka** [comment]
Padding of `tracknumber` tag is available as of the moment of writing:

https://github.com/RecursiveForest/whatmp3/blob/6b0fe1ec60881a48c0a3b18eb57fd8a388c60a43/whatmp3.py#L26-L27
https://github.com/RecursiveForest/whatmp3/blob/6b0fe1ec60881a48c0a3b18eb57fd8a388c60a43/whatmp3.py#L243-L245

I would disagree that padding a `tracknumber` tag is the best practice though. In any sane language if we compare `'1'` and `'10'` string literals this will be true: `'1' < '10'`. So virtually any software asked to sort tracks by its `tracknumber` tag will do such job as you expect it to. Hence padding `traknumber` tag is redundant.

Padding track numbers in file names is undoubtedly useful and can be recommended to one and every.
But it's not that straightforward to implement in this scipt though. You either need to generate file name by a tag pattern or analyze it somehow. Former relies on proper tags, latter is even less reliable. So, script simply leaves file names untouched, only adjusts the extension.

**Comment by RecursiveForest** [comment]
Hey folks. You can change the settings to enable padding of both the tag & filename (but not just one or the other) by enabling the zeropad option -- the point is to make albums with more than 9 tracks display correctly in a directory listing. I'd be willing to entertain the option of not zeropadding the tag (just the filename) if someone wants to prepare a PR.
