### ISSUE TITLE
flag to not copy files over

### ISSUE THREAD

**Issue by boredness** [RecursiveForest/whatmp3#39]
Currently as it stands it will move over all the non music files over to the transcode folder and create the .torrent file which is sometimes unneeded ie:
-rwxr-x--- 1 x x 7.9M Feb 10 11:16 '01 Ghosts Again.mp3'
-rwxr-x--- 1 x x 833 Feb 10 11:16 '01-Ghosts Again.foo_dr.txt'
-rwxr-x--- 1 x x 481K Feb 10 11:16  folder.jpg
-rwxr-x--- 1 x x  647 Feb 10 11:16  origin.yaml

I would like it to only move over the mp3 to the final folder if possible

**Comment by RecursiveForest** [comment]
For posterity, the `-M` / `--nocopyother` flag will disable this behaviour.
